---
title: "Exploratory Data Analysis"
author: "Owen Finkbeiner"
output: html_notebook
---

```{r}
# Load necessary packages
library(tidyverse)
library(ggplot2)

# Set working directory
setwd("C:\\Users\\owenf\\OneDrive\\Desktop\\NHL Analytics")
```

```{r}
# Goals
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot1 <- team_df %>%
  ggplot(aes_string(colnames(team_df[i]), colnames(team_df[26]))) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0,2.5) +
  ylim(0.2,0.8)
  
  print(plot1)
}
```

```{r}
# Points
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot2 <- team %>%
  ggplot(aes_string(colnames(team[i+1]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0, 3.5) +
  ylim(0.2, 0.8)
  
  print(plot2)
}
```

```{r}
# Shots
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot3 <- team %>%
  ggplot(aes_string(colnames(team[i+2]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0,18) +
  ylim(0.2,0.8)
  
  print(plot3)
}
```

```{r}
# Point Shares
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot4 <- team %>%
  ggplot(aes_string(colnames(team[i+3]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0,0.75) +
  ylim(0.2,0.8)
  
  print(plot4)
}
```

```{r}
# Offensive Point Shares
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot5 <- team %>%
  ggplot(aes_string(colnames(team[i+4]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0,0.75) +
  ylim(0.2,0.8)
  
  print(plot5)
}
```

```{r}
# Defensive Point Shares
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot6 <- team %>%
  ggplot(aes_string(colnames(team[i+5]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0, 0.2) +
  ylim(0.2,0.8)
  
  print(plot6)
}
```

```{r}
# Blocks
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot7 <- team %>%
  ggplot(aes_string(colnames(team[i+6]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0,10) +
  ylim(0.2,0.8)
  
  print(plot7)
}
```

```{r}
# Hits
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot8 <- team %>%
  ggplot(aes_string(colnames(team[i+7]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0,30) +
  ylim(0.2,0.8)
  
  print(plot8)
}
```

```{r}
# Games played
for (i in c(31,40,49,58,67,76,85,94,103,112,121,130)){
  plot9 <- team %>%
  ggplot(aes_string(colnames(team[i-1]), colnames(team[26]))) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0,82) +
  ylim(0.2,0.8)
  
  print(plot9)
}
```

```{r}
team %>%
  ggplot(aes(`avgDPS_D_1-3`, WIN.pct)) +
  geom_point(stat = "identity") +
  geom_smooth(method="lm", se=FALSE) +
  xlim(0, 0.25) +
  ylim(0.2,0.8)
```


```{r}
for (i in c(10,13,17,20,22,40,44,56,65,72,89,100,137,143,150,164,166,171,199,201,204,213,215,218,220,228,245,251,258,303,305,312)){
  plotSignificant <- team %>%
  ggplot(aes_string(colnames(team[i+28]), colnames(team[26]))) +
  geom_point(stat = "identity")
  
  print(plotSignificant)
}
```
```




