---
title: "Import Data"
output: html_notebook
---


```{r}
# Load necessary packages
library(tidyverse)
library(rvest)

library(RCurl)
curlSetOpt(timeout = 0)

options(warn=-1)
```


```{r}
player_stats <- list()
player_info <- list()
team_stats <- list()
goalie_stats <- list()
team_goalie_stats <- list()

j <- 1

for (team in c("DET","NSH","CHI","STL","CBJ","COL","EDM","VAN","CGY","MIN","DAL","SJS","LAK","ANA","NJD","PHI","PIT","NYR","NYI","OTT","BUF","TOR","BOS","MTL","WSH","CAR","FLA","TBL")){
  for (year in c("08","09","10","11","12","13","14","15","16","17","18","19","20")){
    
  
  ####### Read tables from HTML from Hockey Reference #######
    
  
  html <- paste0("https://www.hockey-reference.com/teams/", team, "/20", year, ".html")
  webpage <- read_html(html)
  # Read the html into list of tables
  test <- html_table(webpage, fill=TRUE)
  # Extract the 3rd table for player info
  player_info[[j]] <- test[[3]]
  # Extract the 4th table for player stats
  player_stats[[j]] <- test[[4]]
  # Extract the 5th table for goalie stats
  goalie_stats[[j]] <- test[[5]]
  
  
  ####### Wrangle data from player information table and clean data #######
  
  
  # Filter out all goalies
  player_info[[j]] <- filter(player_info[[j]], Pos != "G")
  # Separate height into feet and inches
  player_info[[j]] <- player_info[[j]] %>%
    separate(Ht, into = c("Ht-feet","Ht-inches"))
  # Change to numeric values
  player_info[[j]]$`Ht-feet` <- as.numeric(player_info[[j]]$`Ht-feet`)
  player_info[[j]]$`Ht-inches` <- as.numeric(player_info[[j]]$`Ht-inches`)
  # Calculate height in total number of inches
  player_info[[j]] <- player_info[[j]] %>%
    mutate(Ht = (`Ht-feet`)*12 + `Ht-inches`) %>%
    select(!`Ht-feet`) %>%
    select(!`Ht-inches`)
  # Add team played for into player data frame
  player_info[[j]]$Team = paste0(team, year)
  # Change number and experience to integer
  player_info[[j]]$No. <- as.integer(player_info[[j]]$No.)
  player_info[[j]]$Exp <- as.integer(player_info[[j]]$Exp)
  
  
  ####### Wrangle data from player stats table. Make the following dataframes.     #######
  ####### player_stats is for all of the players' stats for that season.           #######
  ####### team_stats is for the team's overall statistics for that season.         #######
  
  
  # Make first row header
  names(player_stats[[j]]) <- as.matrix(player_stats[[j]][1, ]) #sets first row as column names
  player_stats[[j]] <- player_stats[[j]][-1, ] #remove header column of data frame
  # Rename columns
  colnames(player_stats[[j]]) <- c("Rk","Player","Age","Pos","GP","G","A","PTS","PlusMinus","PIM","G.EV","G.PP","G.SH","G.GW","A.EV","A.PP","A.SH","S","S_pct","TOI","ATOI","OPS","DPS","PS","BLK","HIT","FOW","FOL","FO_pct")
  # Remove last row and make it into a separate data frame
  team_stats[[j]] <- tail(player_stats[[j]], n=1)
  player_stats[[j]] <- player_stats[[j]][-nrow(player_stats[[j]]),]
  # Filter out all goalies
  player_stats[[j]] <- filter(player_stats[[j]], Pos != "G")
  # Change player to team and drop some columns
  team_stats[[j]]$Player[1] <- paste0(team, year)
  team_stats[[j]] <- team_stats[[j]] %>%
    rename(team = Player) %>%
    select(-Rk,-Pos,-Age,-TOI,-ATOI)
  # Add team played for into player data frame
  player_stats[[j]]$Team = paste0(team, year)
  # Add year
  player_stats[[j]]$Year = year
  
  
  ####### Wrangle data from goalie stats table and make following dataframes.                 #######
  ####### goalie_stats is for all of the goalies' stats for that season.                      #######
  ####### team_goalie_stats is for the team's goalies' overall statistics for that season.    #######
  
  
  # Make first row header
  names(goalie_stats[[j]]) <- as.matrix(goalie_stats[[j]][1, ]) #sets first row as column names
  goalie_stats[[j]] <- goalie_stats[[j]][-1, ] #remove header column of data frame
  # Rename columns
  colnames(goalie_stats[[j]]) <- c("Rk","Player","Age","GP","GS","W","L","OTL","GA","SA","SV","SV_pct","GAA","SO","MIN","QS","QS_pct","RBS","GA_pct","GSAA","adjGAA","GPS")
  # Remove last row and make it into a separate data frame
  team_goalie_stats[[j]] <- tail(goalie_stats[[j]], n=1)
  goalie_stats[[j]] <- goalie_stats[[j]][-nrow(goalie_stats[[j]]),]
  # Change name to team and drop some columns
  team_goalie_stats[[j]]$Player[1] <- paste0(team, year)
  team_goalie_stats[[j]] <- team_goalie_stats[[j]] %>%
    rename(team = Player) %>%
    select(-Rk, -Age, -GS)
  # Add team played for into goalie data frame
  goalie_stats[[j]]$Team = paste0(team, year)
  
  
  
  # Add 1 to j to continue loop
  j <- j + 1
}
}
```


























